blog_project/blog/urls.py
from django.conf.urls import url

from blog import views


app_name='blog'

urlpatterns=[
    url(r'^$',views.postlistview.as_view(),name='post_list'),
    url(r'^about/$',views.aboutview.as_view(),name='about'),
    url(r'^post/(?P<pk>\d+)$',views.postdetailview.as_view(),name='detail'),
    url(r'^post/new/$',views.createpostview.as_view(),name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$',views.updatepostview.as_view(),name='post_edit'),
    url(r'^post/(?P<pk>\d+)/delete/$',views.postdeleteview.as_view(),name='post_delete'),
    url(r'^drafts/$',views.draftlistview.as_view(),name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/comment/$',views.add_comment_to_post,name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$',views.comment_approve,name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$',views.comment_remove,name='comment_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$',views.post_publish,name='post_publish'),
]

blog_project/blog_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.contrib.auth import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),
    url(r'^accounts/login/$',views.login,name='login'),
    url(r'accounts/logout/$',views.logout,name='logout',kwargs={'next_page':'/'}),


]

blog_project/blog/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone

# Create your models here.

class post(models.Model):
    author=models.ForeignKey('auth.User')
    text=models.TextField()
    title=models.CharField(max_length=200)
    create_time=models.DateTimeField(default=timezone.now)
    published_date=models.DateTimeField(null=True,blank=True)


    def publish(self):
        self.published_date=timezone.now()
        self.save()

    def approve_comment(self):
        return self.comments.filter(approved_comment=True)
    def get_absolute_url(self):
        return reverse("blog:detail",kwargs={'pk':self.pk})
    def __str__(self):
        return self.title


class comments(models.Model):
    post=models.ForeignKey('blog.post',related_name='comments')
    author=models.CharField(max_length=200)
    text=models.TextField()
    create_time=models.DateTimeField(default=timezone.now)
    approved_comment =models.BooleanField(default=False)


    def approve(self):
        self.approved_comment=True
        self.save()

    def get_absolute_url(self):
        return reverse('post_list')

    def __str__(self):
        return self.text

blog_project/blog/forms.py
from django import forms
from blog.models import post,comments

class postform(forms.ModelForm):

    class Meta():
        model=post
        fields=('author','title','text')

        widgets={
            'title':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }



class commentform(forms.ModelForm):

    class Meta():
        model=comments
        fields=('author','text')

        widgets={
            'author':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea'})
        }

blog_project/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import (TemplateView,ListView
                                  ,DetailView,CreateView,
                                  UpdateView,DeleteView)
from blog.models import post,comments
from django.contrib.auth.mixins import LoginRequiredMixin
from blog.forms import postform,commentform
from django.urls import reverse_lazy
from django.utils import timezone
from django.contrib.auth.decorators import login_required
# Create your views here.

class aboutview(TemplateView):
    template_name='about.html'


class postlistview(ListView):
    model= post


    def get_queryset(self):
        return post.objects.filter(published_date__lte= timezone.now()).order_by('-published_date')

class postdetailview(DetailView):
    model=post


class createpostview(LoginRequiredMixin,CreateView):

    login_url='/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = postform
    model= post

class updatepostview(LoginRequiredMixin,UpdateView):
    model=post
    login_url='/login/'
    redirect_field_name='blog/post_detail.html'
    form_class = postform


class postdeleteview(LoginRequiredMixin,DeleteView):
    model=post
    success_url = reverse_lazy('blog:post_list')


class draftlistview(LoginRequiredMixin,ListView):
    login_url='/login/'
    redirect_field_name = 'blog/post_list.html'
    model=post

    def get_queryset(self):
        return post.objects.filter(published_date__isnull=True).order_by('create_time')


#####################################
#####################################comment section



@login_required
def post_publish(request,pk):
    Post=get_object_or_404(post,pk=pk)
    Post.publish()
    return redirect('blog:detail',pk=pk)


@login_required
def add_comment_to_post(request,pk):
    Post=get_object_or_404(post,pk=pk)# if the post exists then return the post or return 404 error

    if request.method =='POST':
        form=commentform(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=Post# the post which we made eright now should be equal to post object in models
            comment.save()
            return redirect('blog:detail',pk=Post.pk)
    else:
        form=commentform()
    return render(request,'blog/comment_form.html',{'form':form})

@login_required
def comment_approve(request,pk):
    comment=get_object_or_404(comments,pk=pk)
    comment.approve()
    return redirect('blog:detail',pk=comment.post.pk)

@login_required
def comment_remove(request,pk):
    comment=get_object_or_404(comments,pk=pk)
    post_pk=comment.post.pk
    comment.delete()
    return redirect('blog:detail',pk=post_pk)

blog_project/blog/templates/blog/about.html
{% extends 'blog/base.html'%}


{% block body_block %}
<h1>
    About this company
    <p>Thanks for checking it out</p>
</h1>


{% endblock %}

blog_project/blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
    <meta charset="utf-8">
    <title>
        BLOG
    </title>
   
    <!-- bootstrap -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">


    <!-- medium style editor -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">


    <!--fonts -->
   <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One|Ubuntu" rel="stylesheet">
</head>

<body>
<!-- navbar -->

<nav class="navbar navbar-default techfont custom-navbar">

    <div class="container">
        <ul class="nav navbar-nav">
        <li><a class="navbar-brand bigbrand" href="{% url 'blog:post_list' %}">My Blog</a></li>
        <li><a href="{% url 'blog:about' %}"></a></li>
        <li><a href="https://in.linkedin.com/">Linkedin</a></li>
        <li><a href="https://github.com/">Github</a></li>

        </ul>

        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="{% url 'blog:post_new' %}">New Post</a></li>
            <li><a href="{% url 'blog:post_draft_list' %}">Drafts</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
            <li>
                <a>Welcome:{{user.username}}</a>
            </li>

            {% else %}
            <li><a class="nav navbar-right" href="{% url 'login' %}"><span class="glyphicon glyphicon-user"></span></a></li>

            {% endif %}


        </ul>
    </div>



</nav>




<!-- block -->
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            <div class="blog_posts">
                {% block body_block%}

                {% endblock %}

            </div>
        </div>

    </div>
</div>


</body>



</html>

blog_project/blog/templates/blog/comment_form.html
{% extends 'blog/base.html'%}
{% block body_block %}
<h1>New Comment</h1>
<form class="post-form" method="post">
  {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default">Post Comment</button>
</form>
<script>var editor=new MediumEditoe('.editable');</script>

{% endblock %}

blog_project/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html'%}


{% block body_block %}

<form method="post">
    {%csrf_token%}
    <p>Are you sure to want to delete {{obeject}}?</p>
    <input type="submit" class="btn btn-danger" value="confirm">
</form>

{% endblock %}

blog_project/blog/templates/blog/post_detail.html
{% extends 'blog/base.html'%}

{% block body_block %}


<h1 class="posttitle loader">{{post.title}}</h1>
{% if post.published_date %}
<div class="date postdate">
    {{post.published_date}}

</div>
{% else %}
<a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
{% endif %}

<p class="postcontent">{{post.text|safe|linebreaksbr}}</p>

{% if user.is_authenticated %}
<a class="btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}">
    <span class="glyphicon glyphicon-pencil"></span>

</a>
<a class="btn btn-primary" href="{% url 'blog:post_delete' pk=post.pk%}"><span class="glyphicon glyphicon-remove"></span></a>
{% endif %}

<hr>

<a class="btn btn-primary btn-comment" href="{% url 'blog:add_comment_to_post' pk=post.pk%}">Add Comment</a>
<div class="container">
    {% for comment in post.comments.all %}
    <br>
    {% if user.is_authenticated or comment.approved_comment %}

    {{comment.create_time}}
        {% if not comment.approved_comment %}
        <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}">
        <span class="glyphicon glyphicon-remove"></span>

        </a>
        <a class="btn btn-primary" href="{% url 'blog:comment_approve' pk=comment.pk%}">
        <span class="glyphicon glyphicon-ok"></span></a>
{% endif %}

<p>{{comment.text|safe|linebreaks}}</p>
    <p>Posted By:{{comment.author}}</p>

    {% endif %}
    {% empty %}
    <p>NO COMMENTS</p>

    {% endfor %}
</div>

{% endblock %}

blog_project/blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html'%}


{% block body_block %}

{% for post in posts %}
<div class="post">
    <p class="date">Created:{{post.create_time|date:'d-m-y'}}</p>
    <h1><a href="{% url 'blog:detail' pk=post.pk %}">{{post.title}}</a></h1>
    <p>{{post.text|truncatechars:200}}</p>
</div>


{% endfor %}

{% endblock %}

blog_project/blog/templates/blog/post_form.html
{% extends 'blog/base.html'%}
{% block body_block %}

<h1>New Post</h1>
<form class="post-form" method="POST">'
{% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default">SAVE</button>

</form>

<script>var editor= new MediumEditor('.editable');</script>


{% endblock %}

blog_project/blog/templates/blog/post_list.html
{% extends 'blog/base.html'%}




{% block body_block %}

<div class="centerstage">

    {% for post in post_list %}
    <div class="post">
        <h1><a href="{% url 'blog:detail' pk=post.pk %}">{{post.title}}</a></h1>
    <div class="date">
        <p>Published on: {{post.published_date|date:"D M Y"}}</p>

    </div>>
        <a href="{% url 'blog:detail' pk=post.pk %}">Comments:{{post.approve_comment.count}}</a>

    </div>
    {% endfor %}
</div>

{% endblock %}