django-site/basicapp/urls.py
from django.conf.urls import url
from basicapp import views

app_name="basicapp"


urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name="user_login"),

]

django-site/django-site/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include,url
from basicapp import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^basicapp/',include('basicapp.urls')),
    url(r'^logout/$',views.user_logout,name="logout"),
    url(r'^special/',views.special,name="special"),
]

django-site/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class userprofileinfo(models.Model):
    user=models.OneToOneField(User)
    #additional fields
    portfolio_site=models.URLField(blank=True)
    #for profile pic user pillow library
    profile_pic=models.ImageField(upload_to="profile_pics",blank=True)


    def __str__(self):
        return self.user.username

django-site/basicapp/forms.py
from django import forms
from basicapp.models import userprofileinfo
from django.contrib.auth.models import User

#this form made from the User library in auth.models
class userform(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password',)


#this form is the actual copy of model that is created in models.py file...named= userprofileinfo
class profileform(forms.ModelForm):

    class Meta():
        model=userprofileinfo
        fields= ('portfolio_site','profile_pic')

django-site/basicapp/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse,HttpResponseRedirect
from basicapp.forms import userform,profileform
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    return render(request,'basicapp/index.html')


def special(request):
    return render(request,'basioapp/index.html')


@login_required()
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):

    registered=False

    if request.method =="POST":
        #get info from both forms
        user_form=userform(data=request.POST)
        profile_form=profileform(data=request.POST)

        #check if both forms are valid
        if user_form.is_valid() and profile_form.is_valid():
            #save user_form to database
            user=user_form.save()

            #hash the password

            user.set_password(user.password)

            user.save()

            #update the profile and profolio site

            profile=profile_form.save(commit=False)

            #set ie to one relationship btw user

            profile.user=user
            #check if profile pic is provided

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
            #now save the form
            profile.save()
            registered=True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form=userform()
        profile_form=profileform()
    return render(request,'basicapp/register.html',{'user_form':user_form,
                                                    'profile_form':profile_form,
                                                    'registered':registered,})


def user_login(request):
    if request.method=="POST":
        username=request.POST.get("username")
        password=request.POST.get("password")

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse("index"))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print("someone tried to login and failed")
            print("USERNAME:{} and password:{}".format(username,password))
            return HttpResponse("invalid account info")

    else:
        return render(request,'basicapp/login.html',{})

django-site/templates/basicapp/base.html
<!DOCTYPE html>
        <html>
<head>
    <title>BASE</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
<nav class="nav navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>
            <li><a class="navbar-link" href="{% url 'basicapp:register'%}">REGISTER</a></li>

            {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">LOGOUT</a></li>
            {% else %}
            <li><a class="navbar-link" href="{% url 'basicapp:user_login'%}">LOGIN</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container">
{% block body_block %}

{% endblock %}


</div>

</body>
</html>

django-site/templates/basicapp/index.html
{% extends "basicapp/base.html" %}

{% block body_block %}
<div class="jumbotron">
    <h1>WELCOME TO USER PAGE</h1>>

 </div>
{% endblock %}

django-site/templates/basicapp/login.html
{%extends 'basicapp/base.html'%}
{% block body_block %}


<div class="jumbotron">
    <h1>Please login</h1>
    <form action="{% url 'basicapp:user_login'%}" method="post" >
        {%csrf_token%}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter usernme">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">
        </form>

    </div>
{% endblock %}

django-site/templates/basicapp/register.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% load staticfiles %}

{% block body_block %}
<div class="jumbotron">
    {% if registered %}
    <h1>THANK YOU FOR REGISTERING</h1>

    {% else %}
    <h1>REGISTER HERE</h1>
    <form enctype="multipart/form-data" method="POST">
       {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="REGISTER">

    </form>
    {% endif %}
</div>
{% endblock %}